### ISSUE TITLE
[Update] : bump python-telegram-bot version to `20.*`

### ISSUE THREAD

**Issue by Abishnoi69** [AnonymousX1025/FallenRobot#118]
Bump python-telegram-bot (`ptb`) version to **Latest**:-  `20.*`

**Comment by ABG1M** [comment]
> bumb python-telegram-bot (`ptb`) version to **Latest**:- `20.*`

Update kro edit se kus na hoga

**Comment by AnonymousX1025** [comment]
> > bumb python-telegram-bot (`ptb`) version to **Latest**:- `20.*`
> 
> Update kro edit se kus na hoga

Cool bano bs*k
