### ISSUE TITLE
fglitch.gif

### ISSUE THREAD

**Issue by RIAN3755** [AnonymousX1025/FallenRobot#72]
https://user-images.githubusercontent.com/128496455/235989634-34b4cd58-bb37-4233-b976-659171b9d6d1.mp4

**Comment by RIAN3755** [comment]
https://user-images.githubusercontent.com/128496455/235989634-34b4cd58-bb37-4233-b976-659171b9d6d1.mp4

**Comment by AnonymousX1025** [comment]
WTF ?
